mysql:
  host: "127.0.0.1"
  port: 3306
  database: "api"
  username: "root"
  password: "secret"

postgre:
  host: "127.0.0.1"
  port: "5432"
  database: "base"
  username: "postgres"
  password: ""

log: "mysql"
source: "api"